/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RoleAffinityTermApplyConfiguration represents a declarative configuration of the RoleAffinityTerm type for use
// with apply.
type RoleAffinityTermApplyConfiguration struct {
	Roles            []string `json:"roles,omitempty"`
	Weight           *int32   `json:"weight,omitempty"`
	TopologyTierName *string  `json:"topologyTierName,omitempty"`
	TopologyTier     *int32   `json:"topologyTier,omitempty"`
}

// RoleAffinityTermApplyConfiguration constructs a declarative configuration of the RoleAffinityTerm type for use with
// apply.
func RoleAffinityTerm() *RoleAffinityTermApplyConfiguration {
	return &RoleAffinityTermApplyConfiguration{}
}

// WithRoles adds the given value to the Roles field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Roles field.
func (b *RoleAffinityTermApplyConfiguration) WithRoles(values ...string) *RoleAffinityTermApplyConfiguration {
	for i := range values {
		b.Roles = append(b.Roles, values[i])
	}
	return b
}

// WithWeight sets the Weight field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Weight field is set to the value of the last call.
func (b *RoleAffinityTermApplyConfiguration) WithWeight(value int32) *RoleAffinityTermApplyConfiguration {
	b.Weight = &value
	return b
}

// WithTopologyTierName sets the TopologyTierName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TopologyTierName field is set to the value of the last call.
func (b *RoleAffinityTermApplyConfiguration) WithTopologyTierName(value string) *RoleAffinityTermApplyConfiguration {
	b.TopologyTierName = &value
	return b
}

// WithTopologyTier sets the TopologyTier field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TopologyTier field is set to the value of the last call.
func (b *RoleAffinityTermApplyConfiguration) WithTopologyTier(value int32) *RoleAffinityTermApplyConfiguration {
	b.TopologyTier = &value
	return b
}
