apiVersion: workload.serving.volcano.sh/v1alpha1
kind: ModelServing
metadata:
  name: test-ranktable-cce
  namespace: default
spec:
  replicas: 1  # 1 serving group
  plugins:
    - name: ranktable
      type: BuiltIn
      config:
        template: "ascend-ranktable-template-mindie-role-cce"
  template:
    roles:
      - name: inference
        replicas: 2  # 1 role replica
        entryTemplate:  # 1 entry pod
          spec:
            containers:
              - name: entry
                image: alpine:latest
                command: ["sleep", "infinity"]
                resources:
                  limits:
                    huawei.com/ascend-1980: "2"
                  requests:
                    huawei.com/ascend-1980: "2"
        workerReplicas: 1  # 1 worker pod
        workerTemplate:
          spec:
            containers:
              - name: worker
                image: alpine:latest
                command: ["sleep", "infinity"]
                resources:
                  limits:
                    huawei.com/ascend-1980: "2"
                  requests:
                    huawei.com/ascend-1980: "2"
