apiVersion: workload.serving.volcano.sh/v1alpha1
kind: ModelServing
metadata:
  name: test-ranktable-group-cce
  namespace: default
spec:
  replicas: 1
  plugins:
    - name: ranktable
      type: BuiltIn
      config:
        template: ascend-ranktable-template-mindie-group-cce
  template:
    roles:
      - name: prefill
        replicas: 1
        entryTemplate:
          spec:
            containers:
              - name: entry
                image: alpine:latest
                command: ["sleep", "infinity"]
                resources:
                  limits:
                    huawei.com/ascend-1980: "1"
                  requests:
                    huawei.com/ascend-1980: "1"
        workerReplicas: 2
        workerTemplate:
          spec:
            containers:
              - name: worker
                image: alpine:latest
                command: ["sleep", "infinity"]
                resources:
                  limits:
                    huawei.com/ascend-1980: "1"
                  requests:
                    huawei.com/ascend-1980: "1"
      - name: decode
        replicas: 1
        entryTemplate:
          spec:
            containers:
              - name: entry
                image: alpine:latest
                command: ["sleep", "infinity"]
                resources:
                  limits:
                    huawei.com/ascend-1980: "1"
                  requests:
                    huawei.com/ascend-1980: "1"
        workerReplicas: 1
        workerTemplate:
          spec:
            containers:
              - name: worker
                image: alpine:latest
                command: ["sleep", "infinity"]
                resources:
                  limits:
                    huawei.com/ascend-1980: "1"
                  requests:
                    huawei.com/ascend-1980: "1"
