apiVersion: workload.serving.volcano.sh/v1alpha1
kind: ModelServing
metadata:
  name: test-ranktable-group-cce
  namespace: default
spec:
  replicas: 1  # 1 serving group
  plugins:
    - name: ranktable
      type: BuiltIn
      config:
        # Reference to group-level ranktable template
        template: "ascend-ranktable-template-mindie-group-cce"
  template:
    roles:
      # Multiple roles in the same group will share one group-level ranktable ConfigMap
      - name: prefill
        replicas: 1  # 1 role replica
        entryTemplate:  # 1 entry pod
          spec:
            containers:
              - name: entry
                image: alpine:latest
                command: ["sleep", "infinity"]
                resources:
                  limits:
                    huawei.com/ascend-1980: "1"
                  requests:
                    huawei.com/ascend-1980: "1"
        workerReplicas: 2  # 1 worker pod
        workerTemplate:
          spec:
            containers:
              - name: worker
                image: alpine:latest
                command: ["sleep", "infinity"]
                resources:
                  limits:
                    huawei.com/ascend-1980: "1"
                  requests:
                    huawei.com/ascend-1980: "1"

      - name: decode
        replicas: 1  # 1 role replica
        entryTemplate:  # 1 entry pod
          spec:
            containers:
              - name: entry
                image: alpine:latest
                command: ["sleep", "infinity"]
                resources:
                  limits:
                    huawei.com/ascend-1980: "1"
                  requests:
                    huawei.com/ascend-1980: "1"
        workerReplicas: 1  # 1 worker pod
        workerTemplate:
          spec:
            containers:
              - name: worker
                image: alpine:latest
                command: ["sleep", "infinity"]
                resources:
                  limits:
                    huawei.com/ascend-1980: "1"
                  requests:
                    huawei.com/ascend-1980: "1"

# Notes:
# - With group-level ranktable, all pods from all roles in the same serving group
#   will be included in a single ranktable ConfigMap
# - The ConfigMap will be named like: <modelserving-name>-ranktable-<group-name>
# - When a role is scaled down or deleted, the ranktable will be automatically updated
#   to reflect the current state of all pods in the group
# - This is useful for distributed training/inference across multiple roles
